apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaniop
spec:
  template:
    spec:
      containers:
        - name: kaniop
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
