image:
  repository: ghcr.io/pando85/kaniop
  # renovate: datasource=docker depName=ghcr.io/pando85/kaniop
  tag: "latest@sha256:921a27141a2789aee69519d94dd9f45bbae62e054ef74b4bb6cdeccf109ed636"

logging:
  ## Log level defined by RUST_LOG environment variable. Example: info,kaniop=trace
  ## Ref: https://docs.rs/tracing-subscriber/latest/tracing_subscriber/fmt/index.html#filtering-events-with-environment-variables
  level: "info,kaniop=info"

tracing:
  enabled: false
  service: tempo
  namespace: tempo
  port: 4317

resources:
  requests:
    cpu: 10m
    memory: 14Mi
  limits:
    cpu: 2
    memory: 256Mi

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: monitoring

  prometheusRules:
    enabled: true
    additionalLabels:
      release: monitoring
  dashboards:
    enabled: true
    label: grafana_dashboard
    additionalLabels:
      release: monitoring
    annotations:
      grafana.grafana.com/dashboards.target-directory: /tmp/dashboards/kaniop

webhook:
  enabled: true
  image:
    repository: ghcr.io/pando85/kaniop-webhook
    # renovate: datasource=docker depName=ghcr.io/pando85/kaniop-webhook
    tag: "latest@sha256:68fabf7b2e782cba8b72a1c930f00bead15520f7cea8c153118719af499975fb"
  logging:
    ## Log level defined by RUST_LOG environment variable. Example: info,kaniop=trace
    ## Ref: https://docs.rs/tracing-subscriber/latest/tracing_subscriber/fmt/index.html#filtering-events-with-environment-variables
    level: "info,kaniop_webhook=info"
  certManager:
    enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 14Mi
    limits:
      cpu: 2
      memory: 128Mi
