---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-public-users
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: s3-public-users
  data:
    - secretKey: rootUser
      remoteRef:
        key: /s3-public/users
        property: rootUser
    - secretKey: rootPassword
      remoteRef:
        key: /s3-public/users
        property: rootPassword
    - secretKey: readestPassword
      remoteRef:
        key: /s3-public/users
        property: readestPassword
