apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: s3-public
    app.kubernetes.io/name: s3-public
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  name: s3-public
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
