apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ci-runner-data
  labels:
    app.kubernetes.io/name: ci-runner
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-ci-zfspv
  resources:
    requests:
      storage: 64Gi
