apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loki

resources:
  - resources/configmap-grafana-datasource-loki.yaml
  - resources/prometheus-rules-alerts.yaml
  - resources/prometheus-rules-rules.yaml
  - resources/prometheus-rules-vector-alerts.yaml
  - resources/service-monitor.yaml

helmCharts:
  - includeCRDs: true
    name: loki
    namespace: loki
    releaseName: loki
    repo: https://grafana-community.github.io/helm-charts
    valuesFile: values.yaml
    version: 17.1.1
  - name: vector
    repo: https://helm.vector.dev
    version: 0.52.0
    releaseName: vector-agent
    namespace: loki
    includeCRDs: false
    skipTests: true
    valuesFile: vector-agent.yaml
