apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  name: config-stump
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
