apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-datasource-config
  namespace: tempo
  labels:
    grafana_datasource: "1"
data:
  tempo-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Tempo
      type: tempo
      uid: tempo
      access: proxy
      url: http://tempo.tempo.svc.cluster.local:3200
      jsonData:
        tracesToLogsV2:
          datasourceUid: loki
          spanId: spanId
          traceId: traceId
          tags:
            - traceId
          filterByTraceID: true
          filterBySpanID: false
      isDefault: false
      version: 2
