apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pyroscope

resources:
  - resources/configmap-grafana-datasource-pyroscope.yaml
  - resources/prometheus-rules.yaml

helmCharts:
  - name: pyroscope
    repo: https://grafana.github.io/helm-charts
    version: 2.3.2
    releaseName: pyroscope
    namespace: pyroscope
    includeCRDs: true
    valuesFile: values.yaml

configMapGenerator:
  - name: pyroscope-dashboards
    namespace: pyroscope
    files:
      - dashboards/pyroscope-operational.json
generatorOptions:
  annotations:
    grafana.grafana.com/dashboards.target-directory: /tmp/dashboards/pyroscope
    argocd.argoproj.io/sync-options: ServerSideApply=true
  labels:
    grafana_dashboard: "1"
