apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: readest-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: readest-secrets
  data:
    - secretKey: secret
      remoteRef:
        key: /readest/jwt
        property: secret
    - secretKey: anon_key
      remoteRef:
        key: /readest/jwt
        property: anon_key
    - secretKey: service_role_key
      remoteRef:
        key: /readest/jwt
        property: service_role_key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: readest-db-urls
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: readest-db-urls
  data:
    - secretKey: auth_url
      remoteRef:
        key: /readest/db-urls
        property: auth_url
    - secretKey: rest_url
      remoteRef:
        key: /readest/db-urls
        property: rest_url
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: readest-minio-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: readest-minio-secret
  data:
    - secretKey: readestPassword
      remoteRef:
        key: /s3-public/users
        property: readestPassword
