apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: readest-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: readest-secrets
  data:
    - secretKey: secret
      remoteRef:
        key: /readest/jwt
        property: secret
    - secretKey: anon_key
      remoteRef:
        key: /readest/jwt
        property: anon_key
    - secretKey: service_role_key
      remoteRef:
        key: /readest/jwt
        property: service_role_key
