apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: readest
spec:
  kanidmRef:
    name: kanidm
    namespace: kanidm
  displayname: readest
  origin: https://readest.internal.grigri.cloud/
  redirectUrl:
    - https://readest.internal.grigri.cloud/auth/v1/callback
  scopeMap:
    - group: readest-users
      scopes:
        - openid
        - profile
        - email
  preferShortUsername: true
  strictRedirectUrl: true
