apiVersion: v1
kind: ServiceAccount
metadata:
  name: kata-nvidia-coordinator
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kata-nvidia-coordinator
rules:
  - apiGroups:
      - apps
    resources:
      - daemonsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - daemonsets
    resourceNames:
      - kube-system-nvidia-device-plugin
    verbs:
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kata-nvidia-coordinator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kata-nvidia-coordinator
subjects:
  - kind: ServiceAccount
    name: kata-nvidia-coordinator
    namespace: kube-system
