apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: hermes-2
    app.kubernetes.io/name: hermes-2
    backup: hermes-2-zfs
    backup/retain: quaterly
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  name: hermes-2-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
