apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-settings
data:
  settings.yml: |
    use_default_settings: true

    general:
      debug: false
      instance_name: "SearXNG"
      privacypolicy_url: false
      donation_url: false
      contact_url: false
      enable_metrics: true

    search:
      safe_search: 0
      autocomplete: "google"
      default_lang: "es"
      formats:
        - html
        - json

    server:
      secret_key: "env:SEARXNG_SECRET"
      limiter: false
      image_proxy: true
      method: "GET"

    ui:
      static_use_hash: true
      default_theme: simple
      theme_args:
        simple_style: auto

    engines:
      - name: google
        engine: google
        shortcut: g
        disabled: false
        
      - name: duckduckgo
        engine: duckduckgo
        shortcut: ddg
        disabled: false
        
      - name: bing
        engine: bing
        shortcut: b
        disabled: false
        
      - name: wikipedia
        engine: wikipedia
        shortcut: wp
        disabled: false
