apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: searxng-secret
  data:
    - secretKey: SEARXNG_SECRET
      remoteRef:
        key: /searxng/secret
        property: secret_key
