apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: searxng

resources:
  - resources/configmap.yaml
  - resources/external-secret.yaml

helmCharts:
  - name: app-template
    namespace: searxng
    releaseName: searxng
    repo: https://bjw-s-labs.github.io/helm-charts/
    valuesFile: searxng.yaml
    version: 5.1.0
