{
 "title": "SMART disk data",
 "description": "Smartctl data from smartmontools",
 "tags": [
  "smartctl",
  "prometheus"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(smartctl_version,instance)"
    }
   },
   {
    "name": "device",
    "query": {
     "query": "label_values(smartctl_device,device)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Disk Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Media Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (smartctl_device_media_errors{instance=~\"$instance\",device=~\"$device\"})"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(smartctl_device_temperature{ instance=~\"$instance\", device=~\"$device\" }) by (instance, device)",
     "legendFormat": "{{instance}}:/dev/{{device}}"
    }
   ]
  },
  {
   "title": "Critical Warning",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (smartctl_device_critical_warning{instance=~\"$instance\", device=~\"$device\"})"
    }
   ]
  },
  {
   "title": "Active Devices",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (smartctl_device_smart_status{instance=~\"$instance\",device=~\"$device\"})"
    }
   ]
  },
  {
   "title": "Rellocated Event Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(smartctl_device_attribute{instance=~\"$instance\", device=~\"$device\", attribute_name=\"Reallocated_Event_Count\",attribute_value_type=\"raw\"}) by (instance, device)",
     "legendFormat": "{{instance}}:/dev/{{device}}"
    }
   ]
  },
  {
   "title": "Disk Lifetime",
   "type": "table",
   "description": "power on hours:\nyellow after 3 year\nred after 5 years",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_join(smartctl_device_power_on_seconds{instance=~\"$instance\", device=~\"$device\"}, \"id\", \":\", \"instance\", \"device\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(smartctl_device_power_cycle_count{instance=~\"$instance\", device=~\"$device\"}, \"id\", \":\", \"instance\", \"device\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SSD Specific Values",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "SSD Status",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "label_join(smartctl_device_attribute{attribute_name=\"Remaining_lifetime\", instance=~\"$instance\", device=~\"$device\"}, \"id\", \":\", \"instance\", \"device\")",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_join(smartctl_device_attribute{attribute_name=\"Host_sector_write\", instance=~\"$instance\", device=~\"$device\"}, \"id\", \":\", \"instance\", \"device\")",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "HDD Specific Values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Spin Up Time",
   "type": "timeseries",
   "description": "Average time to spin up disk. (in ms)\nHigh values indicate problems with the motor.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(smartctl_device_attribute{attribute_name=\"Spin_Up_Time\", instance=~\"$instance\", device=~\"$device\", attribute_value_type=\"raw\"}) by (instance, device)",
     "legendFormat": "{{instance}}:/dev/{{device}}"
    }
   ]
  },
  {
   "title": "Raw Read Error Rate",
   "type": "timeseries",
   "description": "Indicates problems with the disk surface (platter that stores the data), the actuator arm, and the read/write head. The higher RAW Read Error Rate, the higher chances of disk failure.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(smartctl_device_attribute{attribute_name=\"Raw_Read_Error_Rate\", instance=~\"$instance\", device=~\"$device\", attribute_value_type=\"raw\"}) by (instance, device)",
     "legendFormat": "{{instance}}:/dev/{{device}}"
    }
   ]
  },
  {
   "title": "Reallocated Sector Count",
   "type": "timeseries",
   "description": "Reallocated sectors count is the number of sectors that are marked as reallocated by the hard drive upon an error. A growing count is generally considered a bad sign and can result in hard drive failure.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(smartctl_device_attribute{attribute_name=\"Reallocated_Sector_Ct\", instance=~\"$instance\", device=~\"$device\", attribute_value_type=\"raw\"}) by (instance, device)",
     "legendFormat": "{{instance}}:/dev/{{device}}"
    }
   ]
  },
  {
   "title": "Current Pending Sector",
   "type": "timeseries",
   "description": "It is a critical parameter and indicates the current count of unstable sectors (waiting for remapping). The raw value of this attribute indicates the total number of sectors waiting for remapping. Later, when some of these sectors are read successfully, the value is decreased. If errors still occur when reading some sector, the hard drive will try to restore the data, transfer it to the reserved disk area (spare area) and mark this sector as remapped.\n\nThis is a critical parameter. Degradation of this parameter may indicate imminent drive failure. Urgent data backup and hardware replacement is recommended.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(smartctl_device_attribute{attribute_name=\"Current_Pending_Sector\", instance=~\"$instance\", device=~\"$device\", attribute_value_type=\"raw\"}) by (instance, device)",
     "legendFormat": "{{instance}}:/dev/{{device}}"
    }
   ]
  },
  {
   "title": "Offline Uncorrectable",
   "type": "timeseries",
   "description": " This attribute indicates the total number of uncorrectable errors when reading data from the disk during offline testing.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(smartctl_device_attribute{attribute_name=\"Offline_Uncorrectable\", instance=~\"$instance\", device=~\"$device\", attribute_value_type=\"raw\"}) by (instance, device)",
     "legendFormat": "{{instance}}:/dev/{{device}}"
    }
   ]
  },
  {
   "title": "UDMA CRC Error Count",
   "type": "timeseries",
   "description": "This attribute indicates the number of errors encountered during data transfer via the Ultra DMA interface. CRC errors can be caused by issues such as a faulty or loose data cable, electrical interference, or problems with the drive's controller.\n",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(smartctl_device_attribute{attribute_name=\"UDMA_CRC_Error_Count\", instance=~\"$instance\", device=~\"$device\", attribute_value_type=\"raw\"}) by (instance, device)",
     "legendFormat": "{{instance}}:/dev/{{device}}"
    }
   ]
  },
  {
   "title": "Multi Zone Error Rate",
   "type": "timeseries",
   "description": "This attribute indicates the rate of errors that occur in different zones of the disk during read/write operations. A higher error rate may indicate problems with the disk surface or read/write heads.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(smartctl_device_attribute{attribute_name=\"Multi_Zone_Error_Rate\", instance=~\"$instance\", device=~\"$device\", attribute_value_type=\"raw\"}) by (instance, device)",
     "legendFormat": "{{instance}}:/dev/{{device}}"
    }
   ]
  },
  {
   "title": "HDD Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "label_join(smartctl_device_attribute{attribute_name=\"Power-Off_Retract_Count\", attribute_value_type=\"raw\", instance=~\"$instance\", device=~\"$device\"}, \"id\", \":\", \"instance\", \"device\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(smartctl_device_attribute{attribute_name=\"Start_Stop_Count\", attribute_value_type=\"raw\", instance=~\"$instance\", device=~\"$device\"}, \"id\", \":\", \"instance\", \"device\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(smartctl_device_attribute{attribute_name=\"Load_Cycle_Count\", attribute_value_type=\"raw\", instance=~\"$instance\", device=~\"$device\"}, \"id\", \":\", \"instance\", \"device\")",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Device Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Device Info",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "smartctl_device{instance=~\"$instance\",device=~\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}