[kube_control_plane]
prusik

[kube_node:children]
amd64_node

[amd64_node]
grigri
k8s-amd64-1

[amd64]
prusik
grigri
k8s-amd64-1

[ipmi]
prusik-ipmi

[nvidia]
prusik

[k3s_cluster:children]
kube_control_plane
kube_node
