apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-zfspv
allowVolumeExpansion: true
parameters:
  fstype: "zfs"
  shared: "yes"
  poolname: "fast/db"
provisioner: zfs.csi.openebs.io
allowedTopologies:
  - matchLabelExpressions:
      - key: kubernetes.io/hostname
        values:
          - prusik
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
