{
 "title": "IoT - Climate",
 "tags": [
  "IoT",
  "climate"
 ],
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Energy Consumed",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hass_sensor_energy_kwh{entity=\"sensor.aquarea_dhw_energy_consumed\"}[$__range])) by (entity, friendly_name)",
     "legendFormat": "DHW"
    },
    {
     "expr": "sum(increase(hass_sensor_energy_kwh{entity=\"sensor.aquarea_heat_energy_consumed\"}[$__range])) by (entity, friendly_name)",
     "legendFormat": "Heat"
    },
    {
     "expr": "sum(increase(hass_sensor_energy_kwh{entity=\"sensor.aquarea_cool_energy_consumed\"}[$__range])) by (entity, friendly_name)",
     "legendFormat": "Cool"
    }
   ]
  },
  {
   "title": "Total Energy Produced",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hass_sensor_energy_kwh{entity=\"sensor.aquarea_dhw_energy_produced\"}[$__range])) by (entity, friendly_name)",
     "legendFormat": "DHW"
    },
    {
     "expr": "sum(increase(hass_sensor_energy_kwh{entity=\"sensor.aquarea_heat_energy_produced\"}[$__range])) by (entity, friendly_name)",
     "legendFormat": "Heat"
    },
    {
     "expr": "sum(increase(hass_sensor_energy_kwh{entity=\"sensor.aquarea_cool_energy_produced\"}[$__range])) by (entity, friendly_name)",
     "legendFormat": "Cool"
    }
   ]
  },
  {
   "title": "Average COP",
   "type": "stat",
   "description": "The coefficient of performance or COP (sometimes CP or CoP) of a heat pump, refrigerator or air conditioning system is a ratio of useful heating or cooling provided to work (energy) required.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(sum(hass_sensor_unit_x{domain=\"sensor\", entity=~\"sensor.heishamon_cop\"} > 0)[$__range:])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "DHW", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "DHW Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time((sum(hass_sensor_unit_celsius{domain=\"sensor\", entity=~\"(sensor.aquarea_tank_temperature|sensor.aquarea_tank_target_temperature)\"}) by (entity, friendly_name))[$__interval:])",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "DHW Energy",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sum(increase(hass_sensor_energy_kwh{entity=\"sensor.aquarea_dhw_energy_consumed\"}[$__interval])) by (entity, friendly_name)",
     "legendFormat": "Consumed"
    },
    {
     "expr": "sum(increase(hass_sensor_energy_kwh{entity=\"sensor.aquarea_dhw_energy_produced\"}[$__interval])) by (entity, friendly_name)",
     "legendFormat": "Produced"
    }
   ]
  },
  {
   "title": "DHW Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg_over_time((sum(hass_sensor_power_w{entity=\"sensor.aquarea_dhw_power_consumed\"}) by (entity, friendly_name))[$__interval:])",
     "legendFormat": "{{ friendly_name }}"
    },
    {
     "expr": "avg_over_time((sum(hass_sensor_power_w{entity=\"sensor.aquarea_dhw_power_produced\"}) by (entity, friendly_name)[$__interval:]))",
     "legendFormat": "{{ friendly_name }}"
    },
    {
     "expr": "avg_over_time((sum(hass_sensor_unit_x{domain=\"sensor\", entity=~\"sensor.heishamon_dhw_cop\"}) by (entity, friendly_name))[$__interval:])",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  { "title": "Heat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Heat Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time((sum(hass_sensor_unit_celsius{domain=\"sensor\", entity=~\"(sensor.aquarea_outlet_target_temperature|sensor.aquarea_outlet_temperature)\"}) by (entity, friendly_name))[$__interval:])",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Heat Energy",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sum(increase(hass_sensor_energy_kwh{entity=\"sensor.aquarea_heat_energy_consumed\"}[$__interval])) by (entity, friendly_name)",
     "legendFormat": "Consumed"
    },
    {
     "expr": "sum(increase(hass_sensor_energy_kwh{entity=\"sensor.aquarea_heat_energy_produced\"}[$__interval])) by (entity, friendly_name)",
     "legendFormat": "Produced"
    }
   ]
  },
  {
   "title": "Heat Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg_over_time((sum(hass_sensor_power_w{entity=\"sensor.aquarea_heat_power_consumed\"}) by (entity, friendly_name))[$__interval:])",
     "legendFormat": "{{ friendly_name }}"
    },
    {
     "expr": "avg_over_time((sum(hass_sensor_power_w{entity=\"sensor.aquarea_heat_power_produced\"}) by (entity, friendly_name))[$__interval:])",
     "legendFormat": "{{ friendly_name }}"
    },
    {
     "expr": "avg_over_time((sum(hass_sensor_unit_x{domain=\"sensor\", entity=~\"sensor.heishamon_heat_cop\"}) by (entity, friendly_name))[$__interval:])",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  { "title": "Cool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Cool Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time((sum(hass_sensor_unit_celsius{domain=\"sensor\", entity=~\"(sensor.aquarea_outlet_target_temperature|sensor.aquarea_outlet_temperature)\"}) by (entity, friendly_name))[$__interval:])",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Cool Energy",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sum(increase(hass_sensor_energy_kwh{entity=\"sensor.aquarea_cool_energy_consumed\"}[$__interval])) by (entity, friendly_name)",
     "legendFormat": "Consumed"
    },
    {
     "expr": "sum(increase(hass_sensor_energy_kwh{entity=\"sensor.aquarea_cool_energy_produced\"}[$__interval])) by (entity, friendly_name)",
     "legendFormat": "Produced"
    }
   ]
  },
  {
   "title": "Cool Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg_over_time((sum(hass_sensor_power_w{entity=\"sensor.aquarea_cool_power_consumed\"}) by (entity, friendly_name))[$__interval:])",
     "legendFormat": "{{ friendly_name }}"
    },
    {
     "expr": "avg_over_time((sum(hass_sensor_power_w{entity=\"sensor.aquarea_cool_power_produced\"}) by (entity, friendly_name))[$__interval:])",
     "legendFormat": "{{ friendly_name }}"
    },
    {
     "expr": "avg_over_time((sum(hass_sensor_unit_x{domain=\"sensor\", entity=~\"sensor.heishamon_cool_cop\"}) by (entity, friendly_name))[$__interval:])",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  { "title": "Temperatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Thermostats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time((sum(hass_climate_current_temperature_celsius) by (entity, friendly_name))[$__interval:])",
     "legendFormat": "{{friendly_name}}"
    },
    {
     "expr": "avg_over_time((sum(hass_sensor_unit_celsius{entity=\"sensor.aquarea_outside_ambient_temperature\"}) by (entity, friendly_name))[$__interval:])",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Thermostats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time((sum(hass_climate_current_temperature_celsius) by (entity, friendly_name))[$__interval:])",
     "legendFormat": "{{friendly_name}}"
    },
    {
     "expr": "avg_over_time((sum(hass_climate_target_temperature_celsius) by (entity, friendly_name))[$__interval:])",
     "legendFormat": "Target {{friendly_name}}"
    }
   ]
  },
  { "title": "Energy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Energy Consumed",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sum(increase(hass_sensor_energy_kwh{entity=\"sensor.aquarea_dhw_energy_consumed\"}[$__interval])) by (entity, friendly_name)",
     "legendFormat": "DHW"
    },
    {
     "expr": "sum(increase(hass_sensor_energy_kwh{entity=\"sensor.aquarea_heat_energy_consumed\"}[$__interval])) by (entity, friendly_name)",
     "legendFormat": "Heat"
    },
    {
     "expr": "sum(increase(hass_sensor_energy_kwh{entity=\"sensor.aquarea_cool_energy_consumed\"}[$__interval])) by (entity, friendly_name)",
     "legendFormat": "Cool"
    }
   ]
  },
  {
   "title": "Energy Produced",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sum(increase(hass_sensor_energy_kwh{entity=\"sensor.aquarea_dhw_energy_produced\"}[$__interval])) by (entity, friendly_name)",
     "legendFormat": "DHW"
    },
    {
     "expr": "sum(increase(hass_sensor_energy_kwh{entity=\"sensor.aquarea_heat_energy_produced\"}[$__interval])) by (entity, friendly_name)",
     "legendFormat": "Heat"
    },
    {
     "expr": "sum(increase(hass_sensor_energy_kwh{entity=\"sensor.aquarea_cool_energy_produced\"}[$__interval])) by (entity, friendly_name)",
     "legendFormat": "Cool"
    }
   ]
  },
  {
   "title": "Thermostats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time((sum(hass_sensor_unit_celsius{entity=\"sensor.aquarea_outside_ambient_temperature\"}) by (entity, friendly_name))[$__interval:])",
     "legendFormat": "{{friendly_name}}"
    },
    {
     "expr": "avg_over_time(sum(hass_sensor_unit_x{entity=\"sensor.heishamon_cop\"})[$__interval:])",
     "legendFormat": "COP"
    }
   ]
  },
  {
   "title": "Total Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg_over_time(sum(hass_sensor_power_w{entity=~\"sensor.aquarea_[a-z]*_power_consumed\"})[$__interval:])",
     "legendFormat": "Consumed"
    },
    {
     "expr": "avg_over_time(sum(hass_sensor_power_w{entity=~\"sensor.aquarea_[a-z]*_power_produced\"})[$__interval:])",
     "legendFormat": "Produced"
    },
    {
     "expr": "avg_over_time(sum(hass_sensor_unit_x{domain=\"sensor\", entity=~\"sensor.heishamon_cop\"})[$__interval:])",
     "legendFormat": "COP"
    }
   ]
  },
  { "title": "Aerotherm Interns", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time((sum(hass_sensor_unit_celsius{domain=\"sensor\", entity=~\"(sensor.aquarea_discharge_temperature|sensor.aquarea_eva_outlet_temperature|sensor.aquarea_inside_pipe_temperature|sensor.aquarea_main_hex_outlet_temperature|sensor.aquarea_outlet_target_temperature|sensor.aquarea_outlet_temperature)\"}) by (entity, friendly_name))[$__interval:])",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(hass_sensor_unit_celsius{domain=\"sensor\", entity=~\"(sensor.aquarea_discharge_temperature|sensor.aquarea_inlet_temperature|sensor.aquarea_outlet_temperature|sensor.aquarea_outlet_target_temperature|sensor.aquarea_tank_set_temperature|sensor.aquarea_actual_tank_temperature|sensor.aquarea_outdoor_ambient|sensor.aquarea_outdoor_pipe_temperature|sensor.aquarea_z1_heat_request_temperature|sensor.aquarea_z1_heat_curve_target_high_temperature|sensor.aquarea_z1_heat_curve_target_low_temperature|sensor.aquarea_z1_heat_curve_outside_high_temperature|sensor.aquarea_z1_heat_curve_outside_low_temperature|sensor.aquarea_z2_heat_request_temperature|sensor.aquarea_z2_cool_request_temperature|sensor.aquarea_z1_water_temperature|sensor.aquarea_z2_water_temperature|sensor.aquarea_z1_water_target_temperature|sensor.aquarea_z1_cool_request_temp|sensor.aquarea_z2_water_target_temperature|sensor.aquarea_main_hex_outlet_temperature|sensor.aquarea_inside_pipe_temperature|sensor.aquarea_defrost_temperature|sensor.aquarea_ipm_temperature|sensor.aquarea_eva_outlet_temperature|sensor.aquarea_bypass_outlet_temperature)\"}) by (entity, friendly_name)",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  }
 ]
}