{
 "title": "IoT - Vacuum robot",
 "tags": [
  "IoT",
  "tanque"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Minutes cleaning",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    sum_over_time(hass_binary_sensor_state{entity=\"binary_sensor.valetudo_cleaning\"}[$__range])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Minutes Avg per week in last 3 months",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    sum_over_time(hass_binary_sensor_state{entity=\"binary_sensor.valetudo_cleaning\"}[12w])\n) / 12",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vacuum cleaning status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "max(hass_binary_sensor_state{entity=\"binary_sensor.valetudo_cleaning\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Battery level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(hass_sensor_battery_percent{entity=\"sensor.valetudo_detailedinternalrhinoceros_battery_level\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WiFi strength",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "max(hass_sensor_signal_strength_dbm{entity=\"sensor.valetudo_detailedinternalrhinoceros_wi_fi_configuration\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mop attachment",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "max(hass_binary_sensor_state{entity=\"binary_sensor.valetudo_detailedinternalrhinoceros_mop_attachment\"})",
     "legendFormat": " "
    }
   ]
  }
 ]
}