---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dawarich-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: dawarich-secrets
  data:
    - secretKey: geoapify_api_key
      remoteRef:
        key: /dawarich/geoapify
        property: api-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dawarich-metrics
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: dawarich-metrics
  data:
    - secretKey: username
      remoteRef:
        key: /dawarich/metrics
        property: username
    - secretKey: password
      remoteRef:
        key: /dawarich/metrics
        property: password
