apiVersion: kaniop.rs/v1alpha1
kind: KanidmBackupRepository
metadata:
  name: kanidm
spec:
  s3:
    bucket: kaniop
    prefix: kanidm
    endpoint: https://s3.internal.grigri.cloud
    forcePathStyle: true
  authentication:
    reader:
      secretRef:
        name: kanidm-backup-s3
    writer:
      secretRef:
        name: kanidm-backup-s3
    deleter:
      secretRef:
        name: kanidm-backup-s3
