apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kanidm-backup-s3
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: kanidm-backup-s3
    template:
      data:
        AWS_ACCESS_KEY_ID: kaniop
        AWS_SECRET_ACCESS_KEY: "{{ `{{ .password }}` }}"
  data:
    - secretKey: password
      remoteRef:
        key: /minio/users
        property: kaniopPassword
