---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: hermes
spec:
  kanidmRef:
    name: kanidm
    namespace: kanidm

  displayname: hermes

  origin: https://hermes.internal.grigri.cloud/

  redirectUrl:
    - https://hermes.internal.grigri.cloud/auth/callback

  scopeMap:
    - group: hermes-users
      scopes:
        - openid
        - profile
        - email

  preferShortUsername: true
  strictRedirectUrl: true
