apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: hermes
    app.kubernetes.io/name: hermes
    backup: hermes-zfs
    backup/retain: quaterly
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  name: hermes-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
