apiVersion: snapscheduler.backube/v1
kind: SnapshotSchedule
metadata:
  name: hermes-zfs-backups
spec:
  retention:
    maxCount: 5
  schedule: "0 1 * * *" # UTC
  claimSelector:
    matchLabels:
      backup: hermes-zfs
