{
 "title": "PostgreSQL Database",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "label_values(pg_up, job)" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(up{job=~\"$job\"},namespace)"
   },
   {
    "name": "cluster_name",
    "label": "cluster name",
    "query": "label_values(pg_stat_database_tup_fetched{job=~\"$job\",namespace=~\"$namespace\"},cluster_name)"
   },
   {
    "name": "db",
    "label": "db",
    "query": "label_values(pg_stat_database_tup_fetched{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\",datname!~\"template.*|postgres\"},datname)"
   },
   {
    "name": "spilo_role",
    "label": "spilo role",
    "query": {
     "query": "label_values(pg_stat_database_tup_fetched{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\", datname=~\"$db\"},spilo_role)"
    }
   },
   {
    "name": "mode",
    "label": "Lock table",
    "query": "label_values(pg_locks_count{mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"}, mode)"
   }
  ]
 },
 "panels": [
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Versions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_static{job=~\"$job\",namespace=~\"$namespace\", cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Current fetch data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_fetched{datname=~\"$db\",spilo_role=~\"$spilo_role\", cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\"})"
    }
   ]
  },
  {
   "title": "Current insert data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_inserted{job=~\"$job\",namespace=~\"$namespace\", datname=~\"$db\",spilo_role=~\"$spilo_role\", cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\"})"
    }
   ]
  },
  {
   "title": "Current update data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_updated{datname=~\"$db\",spilo_role=~\"$spilo_role\", cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\"})"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_connections{job=~\"$job\",namespace=~\"$namespace\", cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\"}"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "timeseries",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{job=~\"$job\",namespace=~\"$namespace\", cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\"}[5m]) * 1000)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "timeseries",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{job=~\"$job\",namespace=~\"$namespace\", cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\"}[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{job=~\"$job\",namespace=~\"$namespace\", cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\"}[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{job=~\"$job\",namespace=~\"$namespace\", cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  { "title": "Settings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Shared Buffers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\"}"
    }
   ]
  },
  {
   "title": "Effective Cache",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_effective_cache_size_bytes{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\"}"
    }
   ]
  },
  {
   "title": "Maintenance Work Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_maintenance_work_mem_bytes{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\"}"
    }
   ]
  },
  {
   "title": "Work Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_work_mem_bytes{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\"}"
    }
   ]
  },
  {
   "title": "Max WAL Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_wal_size_bytes{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\"}"
    }
   ]
  },
  {
   "title": "Random Page Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_random_page_cost{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\"}"
    }
   ]
  },
  {
   "title": "Seq Page Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_seq_page_cost{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\"}"
    }
   ]
  },
  {
   "title": "Max Worker Processes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_worker_processes{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\"}"
    }
   ]
  },
  {
   "title": "Max Parallel Workers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_parallel_workers{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\"}"
    }
   ]
  },
  { "title": "Database Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Active sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$db\",spilo_role=~\"$spilo_role\", cluster_name=~\"$cluster_name\",state=\"active\"}",
     "legendFormat": "{{datname}} ({{usename}}@{{application_name}})"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\", datname=~\"$db\",spilo_role=~\"$spilo_role\"}[5m])",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\", datname=~\"$db\",spilo_role=~\"$spilo_role\"}[5m])",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "Update data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_updated{datname=~\"$db\",spilo_role=~\"$spilo_role\", cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Fetch data (SELECT)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_fetched{datname=~\"$db\",spilo_role=~\"$spilo_role\", cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Insert data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_inserted{datname=~\"$db\",spilo_role=~\"$spilo_role\", cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Lock tables",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_locks_count{datname=~\"$db\",spilo_role=~\"$spilo_role\", cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\", mode=~\"$mode\"}",
     "legendFormat": "{{datname}},{{mode}}"
    }
   ]
  },
  {
   "title": "Return data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_returned{datname=~\"$db\",spilo_role=~\"$spilo_role\", cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Idle sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$db\",spilo_role=~\"$spilo_role\", cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\", state=~\"idle|idle in transaction|idle in transaction (aborted)\"}",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "Delete data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_deleted{datname=~\"$db\",spilo_role=~\"$spilo_role\", cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\", datname=~\"$db\",spilo_role=~\"$spilo_role\"} / (pg_stat_database_blks_read{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\", datname=~\"$db\",spilo_role=~\"$spilo_role\"} + pg_stat_database_blks_hit{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\", datname=~\"$db\",spilo_role=~\"$spilo_role\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Buffers (bgwriter)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\"}[5m])",
     "legendFormat": "buffers_backend"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_alloc{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\"}[5m])",
     "legendFormat": "buffers_alloc"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\"}[5m])",
     "legendFormat": "backend_fsync"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_checkpoint{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\"}[5m])",
     "legendFormat": "buffers_checkpoint"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_clean{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\"}[5m])",
     "legendFormat": "buffers_clean"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_conflicts{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\", datname=~\"$db\",spilo_role=~\"$spilo_role\"}[5m])",
     "legendFormat": "{{datname}} conflicts"
    },
    {
     "expr": "irate(pg_stat_database_deadlocks{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\", datname=~\"$db\",spilo_role=~\"$spilo_role\"}[5m])",
     "legendFormat": "{{datname}} deadlocks"
    }
   ]
  },
  {
   "title": "Temp File (Bytes)",
   "type": "timeseries",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_temp_bytes{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\", datname=~\"$db\",spilo_role=~\"$spilo_role\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Checkpoint Stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_write_time{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\"}[5m])",
     "legendFormat": "write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk."
    },
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\",spilo_role=~\"$spilo_role\"}[5m])",
     "legendFormat": "sync_time - Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk."
    }
   ]
  }
 ]
}