apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gpu-operator

resources:
  - time-slicing-config.yaml
  - resources/prometheus-gpu-rules.yaml

helmCharts:
  - name: gpu-operator
    repo: https://helm.ngc.nvidia.com/nvidia
    version: v26.7.0
    releaseName: gpu-operator
    namespace: gpu-operator
    includeCRDs: true
    valuesFile: values.yaml

patches:
  - path: cluster-policy-patch.yaml

configMapGenerator:
  - name: dcgm-exporter-dashboard
    files:
      - dashboards/dcgm-exporter.json
generatorOptions:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Replace=true
    grafana.grafana.com/dashboards.target-directory: /tmp/dashboards/gpu
  labels:
    grafana_dashboard: "1"
