apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: z800-nvidia-dcgm-exporter
  labels:
    release: monitoring
spec:
  staticConfigs:
    - targets:
        - z800.grigri:9445
  scrapeInterval: 15s
  relabelings:
    - sourceLabels:
        - __address__
      separator: ":"
      regex: "(.*):(.*)"
      replacement: "${1}"
      targetLabel: instance
      action: replace
    - replacement: nvidia-dcgm-exporter
      targetLabel: job
      action: replace
    - replacement: z800
      targetLabel: hostname
      action: replace
