apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: otel-collector

helmCharts:
  - name: opentelemetry-collector
    repo: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.169.0
    releaseName: otel-collector
    namespace: otel-collector
    valuesFile: values.yaml
