apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: default
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  bgpInstances:
    - name: "instance-64513"
      localASN: 64513
      localPort: 179
      peers:
        - name: "peer-64512"
          peerASN: 64512
          peerAddress: "192.168.192.1"
          peerConfigRef:
            name: default-peer
