apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: default-advertisement
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: "Service"
      selector:
        matchExpressions:
          - key: cilium.io/bgp-skip
            operator: DoesNotExist
      service:
        addresses:
          - LoadBalancerIP
